package com.allchange.mybatis.dao;

import java.util.List;

import com.allchange.mybatis.domain.Booking;
import com.allchange.mybatis.domain.ChkFRB;
import com.allchange.mybatis.domain.ChkRES;
import com.allchange.mybatis.domain.Contact;
import com.allchange.mybatis.domain.ContactGetter;
import com.allchange.mybatis.domain.Detail;
import com.allchange.mybatis.domain.Filter;
import com.allchange.mybatis.domain.GB_CheckOut;
import com.allchange.mybatis.domain.GB_CreateAccommodation;
import com.allchange.mybatis.domain.GB_GPSTrace;
import com.allchange.mybatis.domain.GB_Properties;
import com.allchange.mybatis.domain.GB_Signup;
import com.allchange.mybatis.domain.GB_TrippalCreateRoom;
import com.allchange.mybatis.domain.GB_TrippalDeleteRoom;
import com.allchange.mybatis.domain.GB_TrippalGetLocationList;
import com.allchange.mybatis.domain.GB_TrippalGetPeopleList;
import com.allchange.mybatis.domain.GB_TrippalGetRoom;
import com.allchange.mybatis.domain.GB_TrippalGetShoutList;
import com.allchange.mybatis.domain.GB_TrippalLocationUpdate;
import com.allchange.mybatis.domain.GB_TrippalShout;
import com.allchange.mybatis.domain.GB_Visit;
import com.allchange.mybatis.domain.GHList;
import com.allchange.mybatis.domain.GhSearch;
import com.allchange.mybatis.domain.Guest;
import com.allchange.mybatis.domain.Insert;
import com.allchange.mybatis.domain.Login;
import com.allchange.mybatis.domain.MakeRoom;
import com.allchange.mybatis.domain.Master;
import com.allchange.mybatis.domain.Profile;
import com.allchange.mybatis.domain.Reply;
import com.allchange.mybatis.domain.Reserve;
import com.allchange.mybatis.domain.Reserve_idGetter;
import com.allchange.mybatis.domain.Room;
import com.allchange.mybatis.domain.RoomList;
import com.allchange.mybatis.domain.Rule;
import com.allchange.mybatis.domain.Search;
import com.allchange.mybatis.domain.Signup;
import com.allchange.mybatis.domain.SignupConfirm;
import com.allchange.mybatis.domain.Talk;
import com.allchange.mybatis.domain.UpdateRoom;
import com.allchange.mybatis.domain.WriteLastMessage;
import com.allchange.mybatis.domain.WriteMessage;

public interface UserDao {
	public int insert(Insert in);

	public List<GB_Properties> getProperties(GB_Properties p);
	public List<GB_Visit> getVisit(GB_Visit visit);
	public int fbSignup(GB_Signup gb_signup);
	public List<GB_CreateAccommodation> checkAccommodation(GB_CreateAccommodation ca);
	public int createAccommodation(GB_CreateAccommodation ca);
	public int createAccommodationLog(GB_CreateAccommodation ca);
	public int createShoutLog(GB_CreateAccommodation ca);
	public int deleteShout(GB_CreateAccommodation ca);
	public int updateAccommodation(GB_CreateAccommodation ca);
	public int updateAccommodationLastDTime(GB_CreateAccommodation ca);
	public List<GB_TrippalGetPeopleList> trippalGetPeopleList(GB_TrippalGetPeopleList tgp);
	public List<GB_TrippalGetLocationList> trippalGetLocationList(GB_TrippalGetLocationList tgl);
	public List<GB_TrippalGetShoutList> trippalGetShoutList(GB_TrippalGetShoutList tgs);
	public int trippalShout(GB_TrippalShout ts);
	public int trippalLocationUpdate(GB_TrippalLocationUpdate tlu);
	public int trippalCreateRoom(GB_TrippalCreateRoom tcr);
	public int trippalDeleteRoom(GB_TrippalDeleteRoom tdr);
	public int trippalJoinRoom(GB_TrippalCreateRoom tcr);
	public List<GB_TrippalGetRoom> trippalGetRoom(GB_TrippalGetRoom tgr);
	public int writeGPSTrace(GB_GPSTrace gt);
	public List<GB_GPSTrace> getGPSTrace();
	public int checkOutAccommodation(GB_CheckOut co);
	public int checkOutCreateAccommodationLog(GB_CheckOut co);
	public int checkOutDeleteAccommodation(GB_CheckOut co);
	public List<GB_CheckOut> getCheckOutIdList(GB_CheckOut co);
	
	public int writeMessage(WriteMessage write);
	public int writeLastMessage(WriteLastMessage write);
	public int updateLastMessage(WriteLastMessage write);
	public List<WriteLastMessage> writeLastMessageChk(WriteLastMessage write);
	public List<UpdateRoom> updateRoom(UpdateRoom updateRoom);
	public int makeRoom(MakeRoom makeRoom);
	public List<MakeRoom> getRoomNo(MakeRoom makeRoom);
	public List<MakeRoom> getRoomUserList(MakeRoom makeRoom);
	public List<RoomList> getRoomList(String EMAIL_ID);
	public List<GhSearch> ghSearch(GhSearch search);
	public List<Master> getMasterRegId(Master master);
	public List<Guest> getRegIdCheckoutMember(String DATE);
	public int updateStateFg(String DATE);
	public List<Guest> getRegId(String ID);
	public int checkout(String DTIME);
	public int signup(Signup signup);
	public List<SignupConfirm> signupConfirm(SignupConfirm signupConfirm);
	public List<Login> login(Login login);
	public int setRegid(Login login);
	public List<Reserve_idGetter> getReserveId(Reserve reserve);
	public List<ChkFRB> chkFRB(Reserve reserve);
	public List<ChkFRB> chkResFRB(Reserve reserve);
	public int checkinWalk(Reserve reserve);
	public int checkinRes(Reserve reserve);
	public List<Reserve> chkResDate(Reserve reserve);
	public List<Reserve> chkResId(Reserve reserve);
	public List<Rule> rule(Reserve reserve);
	public List<Room> room(Reserve reserve);
	public List<Profile> profile(String EMAIL_ID);
	public int profileUpdate(Profile profile);
	public List<Reserve> chkRES(ChkRES mChkRES);
	public List<Talk> talk(Reserve reserve);
	public int reply(Reply reply);
	public List<Search> search(); 
	public List<GHList> ghList(Filter filter);
	public List<GHList> ghListInterest(Filter filter);
	public List<Detail> detail(Detail detail);
	public List<Booking> ghBooking(Filter filter);
	public List<Booking> ghBookingInterest(Filter filter);
	public List<Contact> chkContact(Contact contact);
	public int bookingContact(Contact contact);
	public List<ContactGetter> contactGetter(Contact contact);
}
